import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { faRankingStar, faGear, faCircleQuestion, faShieldHalved } from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import ModalPrivacy from './components/modal-privacy'
import ModalRanking from './components/modal-ranking'
import ModalSettings from './components/modal-settings'
import ModalTuto from './components/modal-tuto'
import PageContainer from './components/page-container'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PageContainer>
          {children}
        </PageContainer>
      </body>
    </html>
  )
}
